CodeChain-io/codechain-explorer

src/client/pages/Block/Block.tsx
=> Hide parcel section if parcel is empty

src/components/transaction/TransactionDetails/DetailsByType/AssetMintDetails/AssetMintDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/AssetTransferDetails/AssetTransferDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/ChangeAssetSchemeDetails/ChangeAssetSchemeDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/IncreaseAssetSupplyDetails/IncreaseAssetSupplyDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/SetShardOwnersDetails/SetShardOwnersDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/SetShardUsersDetails/SetShardUsersDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/StoreDetails/StoreDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/WrapCCCDetails/WrapCCCDetails.tsx
Add missing details in TransactionDetails
https://github.com/CodeChain-io/codechain-explorer/issues/72
=> Add missing details in TransactionDetails

src/components/home/LatestBlocks/LatestBlocks.tsx, src/components/home/LatestTransactions/LatestTransactions.tsx, src/pages/Blocks/Blocks.tsx, src/pages/PendingTransactions/PendingTransactions.tsx, src/pages/Transactions/Transactions.tsx, src/utils/Time.ts
This resolves https://github.com/CodeChain-io/codechain-explorer/issues/85
=> Change the granularity of `Last Seen` fields

src/components/transaction/TransactionSummary/AssetIcon.tsx, src/components/transaction/TransactionSummary/TransactionSummary.tsx
This fixes #75 
This patch also refactors TransactionSummary.tsx
=> Fix the input image in the transaction detail page

src/components/header/Header/Header.tsx
It resolves https://github.com/CodeChain-io/codechain-explorer/issues/99
=> Remove the popup that explains the consensus algorithm

src/components/home/Summary/Summary.tsx, src/components/home/Summary/WeeklyChart.tsx
=> Change the summary to show weekly block and transaction log

src/components/home/LatestBlocks/LatestBlocks.tsx, src/components/home/LatestTransactions/LatestTransactions.tsx, src/pages/Blocks/Blocks.tsx, src/pages/PendingTransactions/PendingTransactions.tsx, src/pages/Transactions/Transactions.tsx, src/redux/actions.ts, src/request/RequestServerTime.tsx, src/utils/Time.ts
Calculate the `Last seen` fields by using the server time
This resolves https://github.com/CodeChain-io/codechain-explorer/issues/88
=> Calculate the `Last seen` fields by using the server time

src/components/transaction/TransactionDetails/DetailsByType/AssetTransferDetails/AssetTransferDetails.tsx
=> Add metadata field to AssetTransferDetails

src/components/home/Summary/WeeklyChart.tsx
This fixes the weird graph on the home page.
=> Set the minY of the line chart to 0

src/components/status/ChainInfo/ChainInfo.tsx, src/pages/Status/Status.tsx, src/request/RequestCodeChainStatus.tsx
Block transaction graph and most fields of the CodeChain information (except for NetworkID) are removed.
=> Remove redundant informations in the status page

src/components/block/BlockList/BlockList.tsx, src/components/home/LatestBlocks/LatestBlocks.tsx, src/components/home/LatestTransactions/LatestTransactions.tsx, src/components/platformAddress/AccountDetails/AccountDetails.tsx, src/components/transaction/TransactionDetails/CommonDetails/CommonDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/PayDetails/PayDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/UnwrapCCCDetails/UnwrapCCCDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/WrapCCCDetails/WrapCCCDetails.tsx, src/components/transaction/TransactionListItems/TransactionListItems.tsx, src/index.scss, src/pages/Blocks/Blocks.tsx, src/pages/PendingTransactions/PendingTransactions.tsx, src/pages/Transactions/Transactions.tsx
This resolves https://github.com/CodeChain-io/codechain-explorer/issues/116
=> Change display format of the CCC quantity

src/pages/Blocks/Blocks.tsx, src/pages/PendingTransactions/PendingTransactions.tsx, src/pages/Transactions/Transactions.tsx, src/request/RequestTotalTransactionCount.tsx
This resolves https://github.com/CodeChain-io/codechain-explorer/issues/103
=> Update maxPage when the page is changed

src/components/transaction/TransactionDetails/DetailsByType/AssetTransferDetails/AssetTransferDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/ChangeAssetSchemeDetails/ChangeAssetSchemeDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/UnwrapCCCDetails/UnwrapCCCDetails.tsx, src/components/transaction/TransactionDetails/DetailsByType/WrapCCCDetails/WrapCCCDetails.tsx, src/components/transaction/TransactionDetails/MoreInfo/AssetTransferOrders/AssetTransferOrders.tsx, src/components/transaction/TransactionDetails/MoreInfo/MoreInfo.tsx
This resolves https://github.com/CodeChain-io/codechain-explorer/issues/72
=> Add missing fields in TransactionDetails

src/pages/Transactions/Transactions.tsx
Refactor handling filter changes in transaction list
=> Refactor handling filter changes in transaction list

src/pages/Transactions/Transactions.tsx
Resolves https://github.com/CodeChain-io/codechain-explorer/issues/150
=> Disable type filter changes when transaction list is loading

.travis.yml, package.json
And IMO we don't need to test it on node 8.
=> Upgrade node and yarn to the stable version

src/pages/PlatformAddress/PlatformAddress.tsx
The API will be removed due to its performance issue in the future.
=> Remove the count of the account's balance history

package.json
It requires the indexer version to be higher or equal to 2.1.0.
=> Bump the version to 2.1.0

.travis.yml, package.json, yarn.lock
The versions below 4.12.0 doesn't support node 12 which is LTS now.
=> Support node 12 instead of node 10

src/components/transaction/TransactionSummary/TransactionSummary.tsx, src/pages/Block/Block.tsx, src/pages/PlatformAddress/PlatformAddress.tsx, src/request/ApiRequest.tsx, src/request/RequestAssetInfosByName.tsx, src/request/RequestAssetScheme.tsx, src/request/RequestAssetTransferAddressUTXO.tsx, src/request/RequestAssetTypeUTXO.tsx, src/request/RequestBlock.tsx, src/request/RequestBlockNumber.tsx, src/request/RequestBlockTransactions.tsx, src/request/RequestBlocks.tsx, src/request/RequestCodeChainStatus.tsx, src/request/RequestDailyLogs.ts, src/request/RequestFeeStats.tsx, src/request/RequestIndexerVersion.tsx, src/request/RequestNodeStatus.tsx, src/request/RequestPendingTransactions.tsx, src/request/RequestPing.tsx, src/request/RequestPlatformAddressAccount.tsx, src/request/RequestServerTime.tsx, src/request/RequestSyncStatus.tsx, src/request/RequestTotalBlockCount.tsx, src/request/RequestTotalPlatformBlockCount.tsx, src/request/RequestTransaction.tsx, src/request/RequestTransactions.tsx, src/request/RequestWeeklyLogs.ts
Some libraries types are changed.
=> Fix type errors
